[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"

# Custom domain function redirects (no /.netlify paths allowed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/webhook/paypal"
  to = "/.netlify/functions/paypal-webhook"
  status = 200

# Catch-all for root
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
